import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'fs';
import { join, resolve } from 'path';

/**
 * Extracts the SatLockEscrow ABI from the Hardhat build artifact and writes it to a stable
 * path that backend + frontend can import. Run after `hardhat compile`; idempotent.
 *
 * Outputs:
 *   contracts/artifacts/abi/SatLockEscrow.json     -- ABI array (machine-consumed)
 *   contracts/artifacts/abi/SatLockEscrow.ts       -- TS export with `as const` for viem
 */

const ROOT = resolve(__dirname, '..');
const HARDHAT_ARTIFACT = join(
  ROOT,
  'artifacts',
  'src',
  'SatLockEscrow.sol',
  'SatLockEscrow.json',
);
const OUT_DIR = join(ROOT, 'artifacts', 'abi');

function main() {
  if (!existsSync(HARDHAT_ARTIFACT)) {
    throw new Error(
      `Hardhat artifact not found at ${HARDHAT_ARTIFACT}. Run \`pnpm compile\` first.`,
    );
  }
  const artifact = JSON.parse(readFileSync(HARDHAT_ARTIFACT, 'utf8'));
  if (!Array.isArray(artifact.abi)) throw new Error('artifact.abi missing or malformed');

  mkdirSync(OUT_DIR, { recursive: true });
  writeFileSync(
    join(OUT_DIR, 'SatLockEscrow.json'),
    JSON.stringify(artifact.abi, null, 2) + '\n',
  );

  const ts = [
    '// AUTO-GENERATED by scripts/export-artifacts.ts — do not edit by hand.',
    '// Regenerate after every contract change: `pnpm compile && pnpm export:abi`.',
    '',
    'export const SatLockEscrowAbi = ' + JSON.stringify(artifact.abi, null, 2) + ' as const;',
    '',
    'export type SatLockEscrowAbi = typeof SatLockEscrowAbi;',
    '',
  ].join('\n');
  writeFileSync(join(OUT_DIR, 'SatLockEscrow.ts'), ts);

  console.log(`Wrote ABI artifacts to ${OUT_DIR}`);
}

main();
